---
- name: Install the httpd rpm
  yum: name=httpd

- name: start the httpd service
  service: name=httpd state=started enabled=yes
  notify: restart httpd

- name: install firewalld (when setting up apache)
  yum: name=firewalld

- name: start firewalld
  service: name=firewalld state=started enabled=yes

- name: Open port 80
  firewalld: service=http permanent=true state=enabled
  notify: restart firewalld
    
