---

galaxy_info:
  author: Frogy Yen
  description: Installs latest Nginx version (using packages directly from nginx.org) on CentOS 7
  company:
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.7
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - development
  - web

dependencies: []
