---
# handlers file for ansible-centos7-nginx

- name: restart firewalld
  service: name=firewalld state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart nginx
  service: name=nginx state=restarted
