---
- name: restart httpd
  service: name=httpd state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted
