# -*- mode: ruby -*-
# vi: set ft=ruby :

  VAGRANTFILE_API_VERSION = "2"
  Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# General Vagrant VM configuration.
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end
# Front end server.
  config.vm.define "ng" do |ng|
  ng.vm.hostname = "nginx.test"
  ng.vm.network :private_network, ip: "192.168.60.4"
  end
# Back end server 1.
  config.vm.define "ap" do |ap|
  ap.vm.hostname = "ap.test"
  ap.vm.network :private_network, ip: "192.168.60.5"
  end
# Tomcat server.
  config.vm.define "tom" do |tom|
  tom.vm.hostname = "tom.test"
  tom.vm.network :private_network, ip: "192.168.60.6"
  end
# Provisioning configuration for Ansible. 
#  config.vm.provision "ansible" do |ansible|
#  ansible.playbook = "site.yml"
#  end
 end

